project_id = "fkykpeiqsctlkfbxlwtc"

[functions.send-workshop-notification]
verify_jwt = false

[functions.send-application-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
